#Numpy

In [2]:
import numpy as np

#1.Creating Array

In [ ]:
#create 1D array
arr = np.array([10,20,30])
print(arr)

[10 20 30]


In [ ]:
#Creating 2D array
arr2 = np.array([
    [1,2,3],
     [4,5,6]
    ])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
#creating 3D array
arr3 = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


##2. Understanding Dimensions

In [ ]:
#For 1D array
print("1D array dimension:-",arr.ndim)
print("2D array dimension:-",arr2.ndim)
print("3D array dimension:-",arr3.ndim)

1D array dimension:- 1
2D array dimension:- 2
3D array dimension:- 3


##3.shape

In [ ]:
print("Shape of 1D array:- ",arr.shape)
print("Shape of 2D array:- ",arr2.shape)
print("Shape of 3D array:- ",arr3.shape)

Shape of 1D array:-  (3,)
Shape of 2D array:-  (2, 3)
Shape of 3D array:-  (2, 2, 2)


##4.size

In [ ]:
arr.size

3

In [ ]:
arr2.size

6

In [ ]:
arr3.size

8

In [ ]:
#ItemSize
print(arr.itemsize)
print(arr2.itemsize)
print(arr3.itemsize)

#Each integer occupies 8 bytes

8
8
8


In [ ]:
arr_I = np.array([1.2,2.3,4.5])
arr_I.itemsize

8

In [ ]:
#nbytes = itemsize * size
arr.nbytes

72

##5.Data Types

In [ ]:
#int array
arr.dtype

dtype('int64')

In [ ]:
#float Array
Arr_float = np.array([1.2,2.3,4.5])
Arr_float.dtype

dtype('float64')

##6.Special Arrays

###1.zeros

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

###2.ones

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

###3.Identity Matrix

In [ ]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###4.Empty

In [ ]:
#uninitialized Array
np.empty((3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###5.Diagonal Matrix

In [ ]:
arr = np.diag([3,4,5])
arr

array([[3, 0, 0],
       [0, 4, 0],
       [0, 0, 5]])

In [ ]:
#Extract diagonal
print(np.diag(arr))

[3 4 5]


##7.arange()

np.arange(start, stop , step)

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

##8. linspace() :-Creates equal intervals.

In [ ]:
np.linspace(1,10,5)
#Between 0 and 10 create 5 equal points.

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [6]:
np.logspace(1,4,4)

array([   10.,   100.,  1000., 10000.])

##9.Random Numbers

In [ ]:
#generate Random Float Values
np.random.random((3,3))

array([[0.40766339, 0.20816987, 0.89930016],
       [0.6979516 , 0.35237788, 0.22370386],
       [0.17234509, 0.11601172, 0.19838871]])

In [ ]:
#1D Array
#generate Random Int Values
np.random.randint((1,10,4))

array([0, 5, 3])

In [ ]:
#2D Array
np.random.randint(1,50,(3,3))

array([[21,  4, 31],
       [12, 14, 43],
       [37, 41,  5]])

In [ ]:
np.random.rand(2,3)
#generate Values between 0 to 1

array([[0.08975911, 0.86313955, 0.73340408],
       [0.66195534, 0.39124652, 0.2002558 ]])

In [ ]:
np.random.randn(3,3)
#Values can be positive or negative

array([[ 0.48324122,  1.08346085, -0.34477083],
       [-0.93003126, -0.49532333, -0.24523122],
       [ 0.55310558, -0.13918214, -0.98444163]])

##10.Indexing

###1.positive Indexing

In [ ]:
arr = np.array([10,20,30,40,50])

print("First Element:- ",arr[0])
print("Second Element:- ",arr[1])
print("Third Element:- ",arr[2])
print("Fourth Element:- ",arr[3])
print("Fourth Element:- ",arr[4])

First Element:-  10
Second Element:-  20
Third Element:-  30
Fourth Element:-  40


###2.Negative Indexing

In [ ]:
print("First Element:- ",arr[-5])
print("Second Element:- ",arr[-4])
print("Third Element:- ",arr[-3])
print("Fourth Element:- ",arr[-2])
print("Fourth Element:- ",arr[-1])

First Element:-  10
Second Element:-  20
Third Element:-  30
Fourth Element:-  40
Fourth Element:-  50


##11.Slicing

###1.Positive Slicing

In [ ]:
print(arr[0:5])
print(arr[:3])
print(arr[2:])
print(arr[1:4])

[10 20 30 40 50]
[10 20 30]
[30 40 50]
[20 30 40]


###2.Negative Slicing

In [ ]:
print(arr[-5:])
print(arr[:-2])
print(arr[-3:])
print(arr[-4:-1])

[10 20 30 40 50]
[10 20 30]
[30 40 50]
[20 30 40]


##12.Reshape

In [ ]:
arr = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

##13.Mathematical Operations

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

###1.Addition

In [ ]:
a+b

array([ 6,  8, 10, 12])

###2.Subtraction

In [ ]:
a-b

array([-4, -4, -4, -4])

###3.Multiplication

In [ ]:
a*b

array([ 5, 12, 21, 32])

###4.Square Root

In [ ]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

###5.Square


In [ ]:
np.square(a)

array([ 1,  4,  9, 16])

###6.absolute Value
Remove the negative sign.

In [ ]:
arr = np.array([-1,-2,-3,-4])
np.abs(arr)

array([1, 2, 3, 4])

##14.Statistics

###1.Mean

In [ ]:
stats = np.array([10,20,10,20,20,30,40,50])
print(np.mean(stats))
print(stats.mean())

25.0
25.0


###2.Median

In [ ]:
print(np.median(stats))

20.0


###4.Maximum

In [ ]:
print(stats.max())
print(np.max(stats))

50
50


###5.Minimum

In [ ]:
print(stats.min())
print(np.min(stats))

10
10


###6.Standard Derivation

In [ ]:
np.std(stats)

np.float64(13.228756555322953)

###7.Variance

In [ ]:
np.var(stats)

np.float64(175.0)

##15.Filtering

In [ ]:
stats[stats>25]

array([30, 40, 50])

##16.Sorting

In [ ]:
arr = np.random.randint(1,10,5)
arr

array([3, 7, 5, 4, 9])

In [ ]:
np.sort(arr)

array([3, 4, 5, 7, 9])

##17.Transpose

In [ ]:
arrTranspose = np.array([
    [10,20,30],
    [40,50,60]
    ])
arrTranspose

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
arrTranspose.T

array([[10, 40],
       [20, 50],
       [30, 60]])

In [ ]:
arrTranspose.transpose()

array([[10, 40],
       [20, 50],
       [30, 60]])

##18.Flatten


flatten() converts a multi-dimensional array into a 1D array.

It creates a new copy of the data.



In [ ]:
arrTranspose.flatten()

array([10, 20, 30, 40, 50, 60])

##19.ravel()
Converts a multi-dimensional array into 1D.

Unlike flatten(), it usually returns a view, not a copy.


In [ ]:
arrTranspose.ravel()

array([10, 20, 30, 40, 50, 60])

##20.concatenate
axis=0 → Join rows

axis=1 → Join columns (for 2D arrays)

In [ ]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8])

##21.Stack

In [ ]:
np.stack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.stack((a,b),axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.stack((a,b),axis=1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
#vstack
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
#hstack
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

##22.copy

In [ ]:
new = a.copy()
new

array([1, 2, 3, 4])

##23.view

In [ ]:
newV = a.view()
newV

array([1, 2, 3, 4])